### ISSUE TITLE
Chat tab disapear instead of changing transparancy.

### ISSUE THREAD

**Issue by AlexandreFoley** [Phanx/PhanxChat#7]
Whithout phanxchat, the chat tabs' transparancy increase slightly while the mouse is not over the chat.
With phanxchat the chat tab disapear completly instead of being slightly more transparent.

This happen even when phanxchat is the only mod enabled.

**Comment by Phanx** [comment]
This is intentional. If you want to change it, open PhanxChat/Core.lua and change the relevant global values:

https://github.com/Phanx/PhanxChat/blob/master/Core.lua#L36
